"""Edit Admin model - Removed confirmed*

Revision ID: 05011f2f2b75
Revises: 8e7b01e72242
Create Date: 2018-10-17 15:58:43.046864

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '05011f2f2b75'
down_revision = '8e7b01e72242'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('admin', 'confirmed_on')
    op.drop_column('admin', 'confirmed')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admin', sa.Column('confirmed', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('admin', sa.Column('confirmed_on', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
