"""Add 'updated' field

Revision ID: 0f4bc90c6cd6
Revises: c133a8b3603d
Create Date: 2018-10-09 22:21:21.796213

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0f4bc90c6cd6'
down_revision = 'c133a8b3603d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admin', sa.Column('updated', sa.TIMESTAMP(), nullable=False))
    op.alter_column('admin', 'confirmed',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.add_column('user', sa.Column('updated', sa.TIMESTAMP(), nullable=False))
    op.alter_column('user', 'confirmed',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'confirmed',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.drop_column('user', 'updated')
    op.alter_column('admin', 'confirmed',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.drop_column('admin', 'updated')
    # ### end Alembic commands ###
