"""empty message

Revision ID: 1fb6f45667c1
Revises: 2393523b25d5
Create Date: 2018-10-07 14:23:16.817746

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1fb6f45667c1'
down_revision = '2393523b25d5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'national_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('national_id', sa.INTEGER(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
