"""Flask Login UserMixin

Revision ID: 2393523b25d5
Revises: 5c7318caba4f
Create Date: 2018-10-07 12:49:40.678442

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2393523b25d5'
down_revision = '5c7318caba4f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admin', sa.Column('id', sa.Integer(), nullable=False))
    op.drop_column('admin', 'admin_id')
    op.add_column('county', sa.Column('id', sa.Integer(), nullable=False))
    op.drop_column('county', 'county_id')
    op.add_column('user', sa.Column('id', sa.Integer(), nullable=False))
    op.drop_column('user', 'user_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('user_id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.drop_column('user', 'id')
    op.add_column('county', sa.Column('county_id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.drop_column('county', 'id')
    op.add_column('admin', sa.Column('admin_id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.drop_column('admin', 'id')
    # ### end Alembic commands ###
