"""empty message

Revision ID: 40dbccaf9da2
Revises: af5b8f0b3258
Create Date: 2018-10-07 14:53:00.981196

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '40dbccaf9da2'
down_revision = 'af5b8f0b3258'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('admin', 'id')
    op.add_column('county', sa.Column('county_id', sa.Integer(), nullable=False))
    op.drop_column('county', 'id')
    op.drop_column('user', 'id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('county', sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('county', 'county_id')
    op.add_column('admin', sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
