"""empty message

Revision ID: 42c766505a8a
Revises: 45bedc2ee459
Create Date: 2018-09-28 03:40:10.757126

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '42c766505a8a'
down_revision = '45bedc2ee459'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('county',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sub_county', sa.Integer(), nullable=True),
    sa.Column('sectors', sa.Integer(), nullable=True),
    sa.Column('population', sa.Float(), nullable=True),
    sa.Column('budget', sa.Float(), nullable=True),
    sa.Column('size', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('county')
    # ### end Alembic commands ###
