"""empty message

Revision ID: 49aeafb10324
Revises: e7c5201b8a0a
Create Date: 2018-10-07 14:39:39.967981

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '49aeafb10324'
down_revision = 'e7c5201b8a0a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('county', sa.Column('county_id', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('county', 'county_id')
    # ### end Alembic commands ###
