"""empty message

Revision ID: 55313b359719
Revises: 4d97958f5631
Create Date: 2018-10-02 13:49:37.624478

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '55313b359719'
down_revision = '4d97958f5631'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('confirmed', sa.Boolean(), nullable=False))
    op.alter_column('user', 'last_seen',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'last_seen',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.drop_column('user', 'confirmed')
    # ### end Alembic commands ###
