"""Edit County Field Properties

Revision ID: 931d5a296dc6
Revises: 070e71bc6d8f
Create Date: 2018-10-23 12:25:55.523067

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '931d5a296dc6'
down_revision = '070e71bc6d8f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('county', 'current_budget',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.drop_column('county', 'sub_county')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('county', sa.Column('sub_county', sa.INTEGER(), autoincrement=False, nullable=False))
    op.alter_column('county', 'current_budget',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=False)
    # ### end Alembic commands ###
