"""Edit County Field Input

Revision ID: 946137e14c25
Revises: 931d5a296dc6
Create Date: 2018-10-23 12:36:56.652427

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '946137e14c25'
down_revision = '931d5a296dc6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('county', 'sectors',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('county', 'sectors',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
