"""Set role as user and admin boolean fields

Revision ID: 94642eb73853
Revises: 05011f2f2b75
Create Date: 2018-10-19 23:07:53.139690

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '94642eb73853'
down_revision = '05011f2f2b75'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admin', sa.Column('admin', sa.Boolean(), nullable=False))
    op.add_column('admin', sa.Column('user', sa.Boolean(), nullable=False))
    op.drop_column('admin', 'role')
    op.add_column('user', sa.Column('admin', sa.Boolean(), nullable=False))
    op.add_column('user', sa.Column('user', sa.Boolean(), nullable=False))
    op.drop_column('user', 'role')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('role', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('user', 'user')
    op.drop_column('user', 'admin')
    op.add_column('admin', sa.Column('role', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('admin', 'user')
    op.drop_column('admin', 'admin')
    # ### end Alembic commands ###
