"""empty message

Revision ID: 94a59bb86979
Revises: 39d990de0d97
Create Date: 2018-09-29 03:09:34.911992

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '94a59bb86979'
down_revision = '39d990de0d97'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('county', sa.Column('county_name', sa.String(length=80), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('county', 'county_name')
    # ### end Alembic commands ###
