"""empty message

Revision ID: af5b8f0b3258
Revises: 7afbd69418ba
Create Date: 2018-10-07 14:45:54.668740

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'af5b8f0b3258'
down_revision = '7afbd69418ba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('admin', 'id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('user', 'id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('admin', 'id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
