"""Add County table primary key

Revision ID: dad950bc53e0
Revises: 946137e14c25
Create Date: 2018-10-23 16:11:51.355727

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dad950bc53e0'
down_revision = '946137e14c25'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('county',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('county_name', sa.String(), nullable=False),
    sa.Column('sectors', sa.Integer(), nullable=True),
    sa.Column('population', sa.Integer(), nullable=True),
    sa.Column('current_budget', sa.Float(), nullable=True),
    sa.Column('proposed_budget', sa.Float(), nullable=True),
    sa.Column('size', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('county_name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('county')
    # ### end Alembic commands ###
