"""Edit Admin Database

Revision ID: dc051f8ad79e
Revises: 87b51b62379e
Create Date: 2018-10-10 12:32:49.136003

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dc051f8ad79e'
down_revision = '87b51b62379e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admin', sa.Column('dob', sa.Date(), nullable=True))
    op.add_column('admin', sa.Column('home_county', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('admin', 'home_county')
    op.drop_column('admin', 'dob')
    # ### end Alembic commands ###
