"""Edit County Fields

Revision ID: e547021c99ee
Revises: 043eb7287213
Create Date: 2018-10-23 11:46:38.248821

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e547021c99ee'
down_revision = '043eb7287213'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('county', sa.Column('id', sa.Integer(), nullable=False))
    op.add_column('county', sa.Column('proposed_budget', sa.Float(), nullable=True))
    op.alter_column('county', 'population',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.create_unique_constraint(None, 'county', ['county_name'])
    op.drop_column('county', 'county_code')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('county', sa.Column('county_code', sa.INTEGER(), autoincrement=True, nullable=False))
    op.drop_constraint(None, 'county', type_='unique')
    op.alter_column('county', 'population',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.drop_column('county', 'proposed_budget')
    op.drop_column('county', 'id')
    # ### end Alembic commands ###
