"""empty message

Revision ID: e7c5201b8a0a
Revises: 1fb6f45667c1
Create Date: 2018-10-07 14:38:07.758776

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e7c5201b8a0a'
down_revision = '1fb6f45667c1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('national_id', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'national_id')
    # ### end Alembic commands ###
